const profanityDetector = textInput => {
  // Extended list of common profane words and phrases (case-insensitive matching)
  const profaneWords = [
    'shit',
    'fuck',
    'damn',
    'bitch',
    'crap',
    'asshole',
    'bastard',
    'dick',
    'piss',
    'cunt',
    'slut',
    'whore',
    'nigger',
    'faggot',
    'retard',
    'spic',
    'chink',
    'kike',
    'twat',
    'wanker',
    'motherfucker',
    'fucker',
    'cocksucker',
    'arse',
    'arsehole',
    'bollocks',
    'bugger',
    'bloody',
    'pussy',
    'tits',
    'titfuck',
    'douchebag',
    'fucked up',
    'bullshit',
    'dickhead',
    'dickwad',
    'shithead',
    'fuckface',
    'fuckwit',
    'screw you',
    'blow me',
    'eat shit',
    'go to hell',
    'hell no',
    'fuck off',
    'fuck you',
    'suck my',
    'bitch ass',
    'cock',
    'penis',
    'vagina',
    'anus',
    'boobs',
    'cum',
    'jizz',
    'smegma',
    'sex',
    'blowjob',
    'handjob',
    'jerk off',
    'jack off',
    'nazi',
    'hitler',
    'pedophile',
    'pedo',
    'rapist',
    'rape',
    'kill yourself',
    'kys',
    'die',
    'suicide',
    'kill',
    'stab',
    'strangle',
    'chloroform',
    'roofies',
    // Common obfuscations and variations
    'f*ck',
    'f**k',
    's**t',
    'b!tch',
    'a$$',
    'b!tch',
    'sh!t',
    'f@ck',
    'fu*k',
    'a$$hole',
    'a55hole',
    'b1tch',
    'wh0re',
    'c0ck',
    'c*nt',
    'c*ck',
    'c@ck',
    'f_ck',
    'd1ck',
    'd*ck',
    'd!ck',
    'fagg0t',
    'n1gger',
    'r3tard',
    's!ut',
  ];

  // Convert text input to lowercase for case-insensitive matching
  const lowerCaseInput = textInput.toLowerCase();

  // Check if any profane word or phrase exists in the text input
  return profaneWords.some(word => lowerCaseInput.includes(word));
};

export default profanityDetector;
